Rems 160
mcode/CRD pull request #25
Opened 2022-05-31 21:04 UTC by KeeyanGhoreshi

adds support for new questionnaire types

2022-06-01 17:24 UTC, tstrass requested changes

2022-06-01 17:24 UTC, tstrass commented on resources/src/main/java/org/cdshooks/CoverageRequirements.java
> +  private String questionnaireProviderKnowledgeAssessmentUri;
Shouldn't these be `Prescriber` rather than `Provider`?

2022-06-01 17:24 UTC, tstrass commented on resources/src/main/java/org/cdshooks/CoverageRequirements.java
> +    return this.questionnaireProviderKnowledgeAssessmentUri;
Here as well. These are all named `Provider` but I think should be `Prescriber`?

2022-06-01 20:07 UTC, tstrass commented on resources/src/main/java/org/cdshooks/CoverageRequirements.java
> +    this.questionnairePrescriberEnrollmentUri = questionnaireProviderEnrollmentUri;
Just a local var but still have a "Provider" misname here

2022-06-02 14:11 UTC, smalho01 approved these changes

2022-06-02 14:11 UTC, merged